# ==========================
# NAV2 - Robot Físico (Real)
# ==========================
# ===================== NAVIGATION2 - REAL ROBOT (Jazzy) =====================

amcl:
  ros__parameters:
    use_sim_time: false
    scan_topic: scan
    min_particles: 500
    max_particles: 2000
    laser_model_type: "likelihood_field"

    laser_min_range: 0.15
    laser_max_range: 8.0

    laser_likelihood_max_dist: 2.0
    z_hit: 0.5
    z_short: 0.05
    z_max: 0.05
    z_rand: 0.5
    sigma_hit: 0.2
    lambda_short: 0.1
    update_min_d: 0.20
    update_min_a: 0.20
    resample_interval: 1
    transform_tolerance: 0.3
    tf_broadcast: true
    # FRAMES (coherentes con tu URDF y EKF)
    base_frame_id: "base_link"
    odom_frame_id: "odom"
    global_frame_id: "map"

amcl_map_client:
  ros__parameters:
    use_sim_time: false
amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: false

# -------------------- BT NAVIGATOR --------------------
bt_navigator:
  ros__parameters:
    use_sim_time: false
    global_frame: map
    robot_base_frame: base_link
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"
    bt_loop_duration: 10
    default_server_timeout: 20
    enable_groot_monitoring: false
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_recovery_node_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_round_robin_node_bt_node
      - nav2_transform_available_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_single_trigger_bt_node
      - nav2_navigate_to_pose_action_bt_node
      - nav2_planner_selector_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: false

# -------------------- CONTROLLER SERVER (DWB) --------------------
controller_server:
  ros__parameters:
    use_sim_time: false
    controller_frequency: 10.0
    odom_topic: /odometry/filtered          # <- tu EKF
    min_x_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    failure_tolerance: 0.3
    progress_checker_plugin: "progress_checker"
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]

    progress_checker:
      plugin: "nav2_controller/SimpleProgressChecker"
      required_movement_radius: 0.35
      movement_time_allowance: 12.0

    general_goal_checker:
      plugin: "nav2_controller/SimpleGoalChecker"
      xy_goal_tolerance: 0.10
      yaw_goal_tolerance: 0.25
      stateful: True

    FollowPath:
      plugin: "dwb_core/DWBLocalPlanner"
      debug_trajectory_details: False
      # Límites según tu robot real
      min_vel_x: 0.0
      max_vel_x: 0.22
      max_vel_theta: 0.9
      min_speed_xy: 0.0
      max_speed_xy: 0.22
      min_speed_theta: 0.0

      acc_lim_x: 0.8
      acc_lim_theta: 2.0
      decel_lim_x: -0.8
      decel_lim_theta: -2.0

      vx_samples: 20
      vtheta_samples: 40

      sim_time: 1.5
      linear_granularity: 0.05
      angular_granularity: 0.025
      transform_tolerance: 0.3

      short_circuit_trajectory_evaluation: True
      critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
      BaseObstacle.scale: 0.02
      PathAlign.scale: 32.0
      PathAlign.forward_point_distance: 0.1
      GoalAlign.scale: 24.0
      GoalAlign.forward_point_distance: 0.1
      PathDist.scale: 32.0
      GoalDist.scale: 24.0
      RotateToGoal.scale: 32.0
      RotateToGoal.slowing_factor: 5.0
      RotateToGoal.lookahead_time: -1.0

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: false

# -------------------- COSTMAP LOCAL --------------------
local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: odom
      robot_base_frame: base_link
      update_frequency: 7.0
      publish_frequency: 5.0
      rolling_window: true
      width: 4
      height: 4
      resolution: 0.05
      transform_tolerance: 0.3
      robot_radius: 0.40

      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d/ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 1.8
          clearing: True
          marking: True
          data_type: "LaserScan"
          obstacle_max_range: 3.0
          raytrace_max_range: 3.2
        combination_method: 1

      inflation_layer:
        plugin: "nav2_costmap_2d/InflationLayer"
        inflation_radius: 0.70
        cost_scaling_factor: 3.0

  local_costmap_client:
    ros__parameters:
      use_sim_time: false
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: false

# -------------------- COSTMAP GLOBAL --------------------
global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: false
      global_frame: map
      robot_base_frame: base_link
      update_frequency: 1.0
      publish_frequency: 1.0
      resolution: 0.05
      track_unknown_space: true
      transform_tolerance: 0.5
      robot_radius: 0.40

      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]

      static_layer:
        plugin: "nav2_costmap_2d/StaticLayer"
        map_subscribe_transient_local: True

      obstacle_layer:
        plugin: "nav2_costmap_2d/ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /scan
          max_obstacle_height: 1.8
          clearing: True
          marking: True
          data_type: "LaserScan"
          obstacle_max_range: 3.0
          raytrace_max_range: 3.2

      inflation_layer:
        plugin: "nav2_costmap_2d/InflationLayer"
        inflation_radius: 0.55
        cost_scaling_factor: 3.0

  global_costmap_client:
    ros__parameters:
      use_sim_time: false
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: false

# -------------------- PLANNER (usa SMAC 2D) --------------------
planner_server:
  ros__parameters:
    use_sim_time: false
    expected_planner_frequency: 10.0
    planner_plugins: ["GridBased"]
    GridBased:
      # Opción 1 (recomendada): Smac 2D
      plugin: "nav2_smac_planner/SmacPlanner2D"
      tolerance: 0.5
      downsample_costmap: false
      allow_unknown: true
      smooth_path: true
      use_astar: false

      # Si prefieres Navfn, cambia a:
      # plugin: "nav2_navfn_planner::NavfnPlanner"
      # tolerance: 0.5
      # allow_unknown: true

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: false

# -------------------- RECOVERIES --------------------
recoveries_server:
  ros__parameters:
    use_sim_time: false
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    recovery_plugins: ["spin", "backup", "wait"]
    spin:
      plugin: "nav2_recoveries/Spin"
    backup:
      plugin: "nav2_recoveries/BackUp"
    wait:
      plugin: "nav2_recoveries/Wait"
    global_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.2
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.0

# -------------------- MAP SERVER / SAVER --------------------
map_server:
  ros__parameters:
    use_sim_time: false
    yaml_filename: "/home/leyla/Desktop/mapas/map_cuarto1.yaml"

map_saver:
  ros__parameters:
    use_sim_time: false
    save_map_timeout: 5.0
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65
    map_subscribe_transient_local: True

# -------------------- VELOCITY SMOOTHER --------------------
velocity_smoother:
  ros__parameters:
    use_sim_time: false
    smoothing_frequency: 20.0
    scale_velocities: false
    feedback: "OPEN_LOOP"
    max_velocity: [0.22, 0.0, 0.9]
    min_velocity: [0.0, 0.0, 0.0]
    max_accel:    [0.8, 0.0, 2.0]
    max_decel:    [0.8, 0.0, 2.0]